### ISSUE TITLE
copy-webpack-plugin - > v6 now

### ISSUE THREAD

**Issue by moderndeveloperllc** [jharris4/html-webpack-deploy-plugin#6]
Not a major issue, but copy-webpack-plugin is now 6.0.1. Looks like the major change for your code is that you pass in an object now instead of an array of assets to copy - https://github.com/webpack-contrib/copy-webpack-plugin/releases/tag/v6.0.0

**Comment by jharris4** [comment]
Thanks for the tip, I'll bump the dependency version soon and push out a new version (after testing that it works).

**Comment by jharris4** [comment]
Just published `2.0.8` with updated dependency of copy-webpack-plugin `^6.0.1`.

**Comment by moderndeveloperllc** [comment]
Works great! Thanks
